const c=require('./commerce.cjs');
const cookieName='__Host-ct_session';
function ready(){return process.env.ACCOUNTS_ENABLED==='true'&&!!process.env.NEXT_PUBLIC_SUPABASE_URL&&!!process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY&&!!process.env.STOREFRONT_ORIGIN;}
function token(req){return String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1)||null;}
function cookie(res,value,seconds){res.setHeader('Set-Cookie',`${cookieName}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${seconds}`);}
async function auth(path,method='GET',body,access){const r=await fetch(new URL('/auth/v1/'+path,process.env.NEXT_PUBLIC_SUPABASE_URL),{method,headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json',...(access?{Authorization:'Bearer '+access}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw c.fail(r.status===429?429:401,r.status===429?'Too many attempts. Please wait before trying again.':'Unable to sign in. Request a new code and try again.');return r.status===204?null:r.json();}
async function user(req){if(!ready())throw c.fail(503,'Customer accounts are awaiting connection. Guest checkout is still available.');const access=token(req);if(!access)throw c.fail(401,'Please sign in to access your profile and BOMs.');const u=await auth('user','GET',null,access);if(!u?.id||!u.email_confirmed_at)throw c.fail(401,'Please verify your email.');return {id:u.id,email:u.email,access};}
async function data(u,path,options={}){const r=await fetch(new URL('/rest/v1/'+path,process.env.NEXT_PUBLIC_SUPABASE_URL),{...options,headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+u.access,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(15000)});if(!r.ok)throw c.fail(503,'Your saved information is temporarily unavailable. Please try again.');return r.status===204?null:r.json();}
function profile(body){const result={};for(const [key,max]of Object.entries({name:150,company:150,phone:50,address:1000})){if(typeof body[key]!=='string'||body[key].length>max)throw c.fail(400,'Please check your profile fields.');result[key]=body[key].trim();}return result;}
function bom(body){if(typeof body.name!=='string'||!body.name.trim()||body.name.length>120||typeof body.notes!=='string'||body.notes.length>2000||!Array.isArray(body.items)||!body.items.length||body.items.length>100)throw c.fail(400,'Name your BOM and include 1–100 lines.');const items=body.items.map(x=>{if(!x||typeof x.sku!=='string'||x.sku.length>100||typeof x.notes!=='string'||x.notes.length>1000||!Number.isInteger(x.quantity)||x.quantity<1||x.quantity>999)throw c.fail(400,'Check each BOM reference and quantity (1–999).');return {sku:x.sku.trim(),quantity:x.quantity,notes:x.notes.trim()};});return {name:body.name.trim(),notes:body.notes.trim(),items,review_required:body.review_required===true};}
module.exports={ready,token,cookie,auth,user,data,profile,bom};
