(() => {
  const $=s=>document.querySelector(s), esc=escapeHtml;
  let session=null,boms=[],editingReview=false;
  const status=message=>{if($('#account-status'))$('#account-status').textContent=message;};
  async function api(path,body){const r=await fetch('/api/'+path,{credentials:'same-origin',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let result;try{result=await r.json();}catch{throw Error('This preview is awaiting the customer-account connection. You can still browse and use the cart.');}if(!r.ok)throw Error(result.error||'Unable to complete this request.');return result;}
  function line(item={sku:'',quantity:1,notes:''}){const row=document.createElement('div');row.className='bom-edit-line';row.innerHTML=`<label>Product reference<input data-bom-sku maxlength="100" value="${esc(item.sku||'')}" placeholder="SKU or leave blank for CTE review"></label><label>Quantity<input data-bom-qty type="number" min="1" max="999" step="1" required value="${Number.isInteger(item.quantity)&&item.quantity>0?item.quantity:1}"></label><label>Line notes<input data-bom-note maxlength="1000" value="${esc(item.notes||'')}"></label><button type="button" data-remove-line>Remove</button>`;$('#bom-lines').append(row);}
  function edit(bom={name:'',notes:'',items:[],review_required:false},duplicate=false){$('#bom-form').hidden=false;$('#bom-id').value=duplicate?'':bom.id||'';$('#bom-name').value=duplicate?(bom.name+' (copy)').slice(0,120):bom.name;$('#bom-notes').value=bom.notes||'';editingReview=!!bom.review_required;$('#bom-review').textContent=editingReview?'Draft from AI — CTE must confirm references, quantities, and compatibility.':'CTE must confirm application suitability before ordering.';$('#bom-lines').replaceChildren();(bom.items.length?bom.items:[{}]).forEach(line);$('#bom-name').focus();}
  function describe(items){let total=0,unmatched=0;for(const x of items){const p=state.products.find(p=>String(p.sku)===x.sku);if(!p||p.list_price==null||p.purchasable===false||!Number.isFinite(Number(p.list_price))){unmatched++;continue;}total+=Math.round(quotePrice(p.list_price)*100)*x.quantity;}return `${items.length} lines · Current product subtotal ${money.format(total/100)}${unmatched?` · ${unmatched} reference(s) need review`:''}${state.usingPreview?' · Sample prices in preview':''}`;}
  function renderBoms(){if(!$('#saved-boms'))return;$('#saved-boms').innerHTML=boms.map(b=>`<article class="saved-bom"><h3>${esc(b.name)}</h3><p>${esc(b.notes)}</p><p>${esc(describe(b.items))}</p>${b.review_required?'<p>AI draft — CTE review required</p>':''}<div class="account-toolbar"><button type="button" data-edit-bom="${esc(b.id)}">Edit / Review</button><button type="button" data-copy-bom="${esc(b.id)}">Duplicate</button><button type="button" data-cart-bom="${esc(b.id)}" ${b.review_required?'disabled':''}>Add to cart</button></div></article>`).join('')||'<p>No saved BOMs yet. Create one here, or save your cart as a BOM.</p>';}
  async function loadMember(){const data=await api('customer-data');boms=data.boms;$('#signin-panel').hidden=true;$('#member-panel').hidden=false;$('#member-email').textContent=session.email;for(const name of ['name','company','phone','address'])$('#profile-form').elements[name].value=data.profile?.[name]||'';renderBoms();status('Signed in. Your saved information is private to this account.');
    if(new URLSearchParams(location.search).get('save')==='cart'){let items=[];try{items=JSON.parse(localStorage.getItem('ct-cart-v1')||'[]');}catch{}if(Array.isArray(items)&&items.length)edit({name:'My project BOM',notes:'',items:items.map(x=>({...x,notes:''})),review_required:false});history.replaceState(null,'','./account.html');}
    if(new URLSearchParams(location.search).get('save')==='ai'){let draft;try{draft=JSON.parse(sessionStorage.getItem('ct-ai-bom-draft')||'null');}catch{}if(draft?.items?.length)edit(draft);history.replaceState(null,'','./account.html');}
  }
  async function init(){try{const info=await api('customer-session');session=info.user;document.querySelectorAll('.account-link').forEach(x=>x.textContent=session?'My account':'Sign in / My account');if($('#signin-panel')){if(!info.configured){status('Preview: customer sign-in and saved BOMs need their account connection. Guest checkout does not require an account.');return;}$('#send-code').disabled=false;if(session)await loadMember();else status('Sign in to save your profile and BOMs, or continue as a guest.');}
    if(session&&$('#checkout-form')){const data=await api('customer-data');const form=$('#checkout-form');for(const name of ['name','company','phone','address'])if(!form.elements[name].value)form.elements[name].value=data.profile?.[name]||'';if(!form.elements.email.value)form.elements.email.value=session.email;$('#checkout-account').textContent='Signed in as '+session.email+'. Review your details before submitting.';}
  }catch(e){status(e.message);}}
  function handler(form,fn){$(form)?.addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"],button:not([type])');if(button)button.disabled=true;try{await fn(e.target);}catch(error){status(error.message);}finally{if(button)button.disabled=false;}});}
  handler('#signin-form',async()=>{await api('customer-session',{action:'code',email:$('#signin-email').value.trim()});$('#verify-form').hidden=false;status('Check your email and enter the sign-in code below.');$('#signin-code').focus();});
  handler('#verify-form',async()=>{const result=await api('customer-session',{action:'verify',email:$('#signin-email').value.trim(),code:$('#signin-code').value.trim()});session=result.user;$('#signin-code').value='';await loadMember();});
  handler('#profile-form',async form=>{await api('customer-data',{action:'profile',...Object.fromEntries(new FormData(form))});status('Profile saved.');});
  handler('#bom-form',async()=>{const items=[...$('#bom-lines').children].map(row=>({sku:row.querySelector('[data-bom-sku]').value.trim(),quantity:Number(row.querySelector('[data-bom-qty]').value),notes:row.querySelector('[data-bom-note]').value.trim()}));if(!items.length)throw Error('Add at least one BOM line.');await api('customer-data',{action:'save-bom',id:$('#bom-id').value||null,name:$('#bom-name').value,notes:$('#bom-notes').value,items,review_required:editingReview});$('#bom-form').hidden=true;await loadMember();status('BOM saved. Prices will refresh when you use it.');});
  $('#signout')?.addEventListener('click',async()=>{try{await api('customer-session',{action:'logout'});location.reload();}catch(e){status(e.message);}});
  $('#new-bom')?.addEventListener('click',()=>edit());$('#add-bom-line')?.addEventListener('click',()=>{if($('#bom-lines').children.length<100)line();else status('A BOM can contain up to 100 lines.');});$('#cancel-bom')?.addEventListener('click',()=>{$('#bom-form').hidden=true;});
  document.addEventListener('click',e=>{if(e.target.closest('[data-remove-line]'))e.target.closest('.bom-edit-line').remove();const b=e.target.closest('[data-edit-bom],[data-copy-bom],[data-cart-bom]');if(!b)return;const id=b.dataset.editBom||b.dataset.copyBom||b.dataset.cartBom;const bom=boms.find(x=>x.id===id);if(!bom)return;if(b.dataset.editBom||b.dataset.copyBom){edit(bom,!!b.dataset.copyBom);return;}try{if(bom.review_required)throw Error('This AI draft needs CTE review before it can become an order.');let cart=JSON.parse(localStorage.getItem('ct-cart-v1')||'[]');if(!Array.isArray(cart))cart=[];const merged=new Map();for(const x of [...cart,...bom.items]){const p=state.products.find(p=>String(p.sku)===x.sku);if(!p||p.list_price==null||p.purchasable===false)throw Error('Reference '+(x.sku||'(blank)')+' needs CTE review. Your cart was not changed.');const n=(merged.get(x.sku)||0)+x.quantity;if(!Number.isInteger(n)||n<1||n>999)throw Error('Combined quantities must be 1–999 per reference.');merged.set(x.sku,n);}if(merged.size>100)throw Error('The combined cart exceeds 100 references.');localStorage.setItem('ct-cart-v1',JSON.stringify([...merged].map(([sku,quantity])=>({sku,quantity}))));location.href='./cart.html';}catch(error){status(error.message);}});
  $('#guest-checkout')?.addEventListener('click',()=>{$('#checkout-form').dataset.guest='true';$('#checkout-account').textContent='Continue using the contact details below. An account is not required.';$('#checkout-form').elements.name.focus();});
  window.addEventListener('catalog-loaded',renderBoms);
  init();
})();
