(() => {
 const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let tab='orders',page=1,stage='pending_approval';
 const stages={pending_approval:'Pending orders',approved:'Accepted / Preparing shipment',closed_invoiced:'Closed & invoiced',declined:'Declined',all:'All orders'};
 async function api(path,body){const r=await fetch(path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{status:r.status});return d;}
 const status=t=>$('#status').textContent=t;
 const money=(c,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format(c/100);
 function order(o){const c=o.customer||{};return `<article class="admin-card"><h2>${esc(c.company||c.name||'Order request')}</h2><p>${esc(o.id)} · ${esc(o.created_at)} · ${esc(o.payment_method)}</p><p>${esc(c.name)} · ${esc(c.email)} · ${esc(c.phone)}</p><pre>${esc(c.address)}</pre><p>PO: ${esc(c.po_number||'—')}</p><pre>Customer notes: ${esc(c.notes||'—')}</pre><div class="table-scroll"><table><thead><tr><th>SKU / product</th><th>Quantity</th><th>Unit price</th></tr></thead><tbody>${(o.items||[]).map(i=>`<tr><td>${esc(i.sku)} — ${esc(i.description)}</td><td>${esc(i.quantity)}</td><td>${esc(money(i.unit_price_cents,o.currency))}</td></tr>`).join('')}</tbody></table></div><p><strong>Product subtotal: ${esc(money(o.subtotal_cents,o.currency))}</strong> · Shipping and tax require confirmation.</p><form data-order="${esc(o.id)}"><div class="admin-fields"><label>Order stage<select name="status">${['pending_approval','approved','closed_invoiced','declined'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${stages[s]}</option>`).join('')}</select></label><label>QuickBooks invoice number<input name="invoice_number" maxlength="200" value="${esc(o.invoice_number)}"></label><label>Tracking number<input name="tracking_number" maxlength="200" value="${esc(o.tracking_number)}"></label><label class="wide">Internal notes<textarea name="internal_notes" maxlength="4000">${esc(o.internal_notes)}</textarea></label></div><button>Save order</button><span role="status" class="save-result"></span></form></article>`;}
 function customer(u){const p=u.profile||{};return `<article class="admin-card"><h2>${esc(p.company||p.name||u.email)}</h2><p>${esc(u.email)} · ${esc(p.name)} · ${esc(p.phone)}</p><pre>${esc(p.address)}</pre><p>Registered: ${esc(u.created_at)}<br>Last sign-in: ${esc(u.last_sign_in_at||'Never')}</p><small>${esc(u.id)}</small></article>`;}
 async function load(){status('Loading…');$('#records').replaceChildren();try{const d=await api('/api/admin?tab='+tab+'&page='+page+'&status='+stage);$('#signin').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;$('#order-stages').hidden=tab!=='orders';document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stage===stage)));$('#view-title').textContent=tab==='orders'?stages[stage]:'Customers';$('#records').innerHTML=(tab==='orders'?d.orders.map(order):d.users.map(customer)).join('')||'<p>No records on this page.</p>';$('#page').textContent='Page '+page;$('#previous').disabled=page===1;$('#next').disabled=!d.hasMore;status('');}catch(e){status(e.message);if(e.status===401||e.status===403){$('#dashboard').hidden=true;$('#signin').hidden=false;}}}
 $('#send-code').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await api('/api/customer-session',{action:'code',email:'sales@ctelectricreps.com'});$('#verify-code').hidden=false;status('Check sales@ctelectricreps.com for your code.');}catch(e){status(e.message);}finally{b.disabled=false;}};
 $('#verify-code').onsubmit=async e=>{e.preventDefault();try{await api('/api/customer-session',{action:'verify',email:'sales@ctelectricreps.com',code:e.currentTarget.elements.code.value.trim()});await load();}catch(e){status(e.message);}};
 $('#logout').onclick=async()=>{try{await api('/api/customer-session',{action:'logout'});$('#records').replaceChildren();$('#dashboard').hidden=true;$('#signin').hidden=false;$('#logout').hidden=true;$('#verify-code').reset();status('Signed out.');}catch(e){status(e.message);}};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;page=1;load();});
 document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;page=1;load();});
 $('#previous').onclick=()=>{page--;load();};$('#next').onclick=()=>{page++;load();};$('#refresh').onclick=load;
 $('#records').onsubmit=async e=>{const f=e.target.closest('[data-order]');if(!f)return;e.preventDefault();const b=f.querySelector('button'),msg=f.querySelector('.save-result');b.disabled=true;try{await api('/api/admin',{id:f.dataset.order,...Object.fromEntries(new FormData(f))});await load();status('Order saved.');}catch(e){msg.textContent=' '+e.message;}finally{b.disabled=false;}};
 load();
})();
