(() => {
  const key='ct-cart-v1';
  let cart=[];
  try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))cart=saved.filter(x=>x&&typeof x.sku==='string'&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=999).slice(0,100);}catch{}
  const el=s=>document.querySelector(s),escape=escapeHtml;
  let checkoutReady=false,invoiceReady=false,requestId=null;
  function save(){try{localStorage.setItem(key,JSON.stringify(cart));}catch{}requestId=null;badge();}
  function badge(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cart.reduce((n,x)=>n+x.quantity,0));}
  function add(sku){const product=state.products.find(x=>String(x.sku)===sku);if(!product)return;const old=cart.find(x=>x.sku===sku);if(old){old.quantity=Math.min(999,old.quantity+1);}else{if(cart.length>=100)return;cart.push({sku,quantity:1});}save();el('.cart-toast')?.remove();const toast=document.createElement('div');toast.className='cart-toast';toast.role='status';toast.innerHTML='Added to cart. <a href="./cart.html">View cart</a>';document.body.append(toast);setTimeout(()=>toast.remove(),4000);}
  function addButtons(){document.querySelectorAll('.product-card').forEach(card=>{if(card.querySelector('.add-cart'))return;const sku=card.querySelector('[data-quote-sku]')?.dataset.quoteSku;if(!sku)return;const button=document.createElement('button');button.type='button';button.className='add-cart';button.dataset.addCart=sku;button.textContent='Add to cart';card.querySelector('.product-bottom').append(button);});}
  function renderCart(){if(!el('#cart-items'))return;let subtotal=0;let valid=true;el('#cart-items').innerHTML=cart.map(item=>{const p=state.products.find(x=>String(x.sku)===item.sku);const unit=p?quotePrice(p.list_price):null;const cents=unit==null?null:Math.round(unit*100);if(cents==null||!Number.isFinite(cents))valid=false;else subtotal+=cents*item.quantity;return `<article class="cart-row"><div><small>SKU ${escape(item.sku)}</small><h2>${escape(p?.short_description||'Product unavailable')}</h2><small>${cents==null?'Price requires confirmation':money.format(cents/100)+' each'}</small></div><label>Quantity<input aria-label="Quantity for ${escape(item.sku)}" type="number" min="1" max="999" step="1" value="${item.quantity}" data-cart-quantity="${escape(item.sku)}"></label><strong>${cents==null?'Confirm price':money.format(cents*item.quantity/100)}</strong><button type="button" data-cart-remove="${escape(item.sku)}">Remove</button></article>`;}).join('')||'<p>Your cart is empty. <a href="./products.html">Browse products</a></p>';el('#cart-summary').innerHTML=cart.length?`<h2>Product subtotal: ${money.format(subtotal/100)}</h2><p>Shipping and tax are additional and will be confirmed by CTE.${state.usingPreview?' This preview uses sample product pricing.':''}</p>`:'';el('#checkout-panel').hidden=!cart.length;el('#submit-order').disabled=!checkoutReady||(el('#checkout-form')?.elements.method.value==='qb_invoice'&&!invoiceReady)||!valid||!cart.length||state.usingPreview;}
  document.addEventListener('click',e=>{const addButton=e.target.closest('[data-add-cart]');if(addButton)add(addButton.dataset.addCart);const remove=e.target.closest('[data-cart-remove]');if(remove){cart=cart.filter(x=>x.sku!==remove.dataset.cartRemove);save();renderCart();}});
  document.addEventListener('change',e=>{if(e.target.matches('[data-cart-quantity]')){const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>999){e.target.setCustomValidity('Enter a whole quantity from 1 to 999.');e.target.reportValidity();return;}e.target.setCustomValidity('');cart.find(x=>x.sku===e.target.dataset.cartQuantity).quantity=n;save();renderCart();}});
  const grid=el('#product-grid');if(grid){new MutationObserver(addButtons).observe(grid,{childList:true});addButtons();}
  window.addEventListener('catalog-loaded',()=>{renderCart();addButtons();});badge();if(state.products.length)renderCart();
  async function api(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let result;try{result=await response.json();}catch{throw Error('This feature is not connected in the local preview.');}if(!response.ok)throw Error(result.error||'Unable to complete this request.');return result;}
  if(el('#checkout-form')){
    fetch('/api/commerce-status').then(r=>r.ok?r.json():Promise.reject()).then(s=>{checkoutReady=s.po;invoiceReady=s.qbInvoice===true;el('#checkout-status').textContent=s.po?'Orders require CTE review. QuickBooks invoice payments take place after your final total is confirmed.':'Checkout setup is in progress. Your cart is saved on this device; no order has been submitted.';renderCart();}).catch(()=>{el('#checkout-status').textContent='Preview: your cart works, but order submission and card payments are not connected yet.';});
    const method=el('#checkout-form').elements.method;
    method.addEventListener('change',()=>{const po=method.value==='po';el('#po-number-field').hidden=!po;el('#checkout-form').elements.po_number.required=po;el('#submit-order').textContent=po?'Submit PO for approval':'Request QuickBooks payment invoice';requestId=null;renderCart();});
    el('#checkout-form').addEventListener('input',()=>{requestId=null;});
    el('#checkout-form').addEventListener('submit',async e=>{e.preventDefault();const button=el('#submit-order');button.disabled=true;if(!checkoutReady||(method.value==='qb_invoice'&&!invoiceReady)||state.usingPreview||!cart.length){renderCart();return;}const data=Object.fromEntries(new FormData(e.target));data.guest_checkout=e.target.dataset.guest==='true';requestId ||= crypto.randomUUID();el('#order-result').textContent='Submitting your order request for review…';try{const result=await api('/api/po-order',{...data,items:cart,idempotency_key:requestId});cart=[];save();renderCart();el('#cart-summary').textContent=`Order request ${result.order_id} received for CTE approval. ${data.method==='qb_invoice'?'CTE will prepare your QuickBooks payment invoice after confirming the total. ':''}No payment has been taken.`;}catch(error){el('#order-result').textContent=error.message;renderCart();}});
  }
  if(el('#assistant-form')){el('#analyze-spec').disabled=true;el('#assistant-status').textContent='Checking assistant availability…';fetch('/api/commerce-status').then(r=>r.ok?r.json():Promise.reject()).then(s=>{el('#analyze-spec').disabled=!s.ai;el('#assistant-status').textContent=s.ai?'Ready to analyze your requirements.':'AI setup is in progress. Search the catalog or request help from CTE for now.';}).catch(()=>{el('#assistant-status').textContent='Preview: AI analysis is awaiting connection. Search the catalog or request help from CTE for now.';});}
  if(el('#assistant-form'))el('#assistant-form').addEventListener('submit',async e=>{e.preventDefault();const button=el('#analyze-spec');button.disabled=true;el('#assistant-results').replaceChildren();el('#assistant-status').textContent='Reviewing requirements and catalog references…';try{const file=el('#spec-file').files[0];let pdf=null;if(file){if(file.size>2*1024*1024||!file.name.toLowerCase().endsWith('.pdf'))throw Error('Choose a PDF smaller than 2 MB.');pdf=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read this PDF.'));reader.readAsDataURL(file);});}const result=await api('/api/product-assistant',{question:el('#assistant-request').value,pdf});el('#assistant-status').textContent='Draft suggestions — CTE must confirm ratings, compatibility, quantities, and availability.';const intro=document.createElement('p');intro.textContent=result.summary;el('#assistant-results').append(intro);for(const line of result.lines){const row=document.createElement('article');row.className='bom-line';row.innerHTML=`<h3>${escape(line.requirement)}</h3><p>${escape(line.reason)}</p><p><strong>Quantity:</strong> ${line.quantity==null?'Confirm':line.quantity}</p>${line.sku?`<a href="./products.html?q=${encodeURIComponent(line.sku)}">Review catalog reference ${escape(line.sku)}</a>`:'<p><strong>No verified catalog reference selected.</strong></p>'}<p>${escape(line.gaps.join(' • '))}</p>`;el('#assistant-results').append(row);}const saveLink=document.createElement('a');saveLink.href='./account.html?save=ai';saveLink.textContent='Save draft to my BOMs';saveLink.className='button';saveLink.addEventListener('click',()=>{sessionStorage.setItem('ct-ai-bom-draft',JSON.stringify({name:'AI specification draft',notes:result.summary,review_required:true,items:result.lines.map(x=>({sku:x.sku||'',quantity:x.quantity||1,notes:[x.requirement,x.quantity==null?'Quantity unknown: confirm before ordering.':'',...x.gaps].join(' • ').slice(0,1000)}))}));});el('#assistant-results').append(saveLink);}catch(error){el('#assistant-status').textContent=error.message;}finally{button.disabled=false;}});
})();
